"""add user_id to flashcards

Revision ID: 500927af5b3e
Revises: a9c64b0a5993
Create Date: 2026-07-12 13:45:44.343581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500927af5b3e'
down_revision: Union[str, None] = 'a9c64b0a5993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_flashcards_id', table_name='flashcards')
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_flashcards_user_id_users'), 'flashcards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_constraint(op.f('fk_flashcards_user_id_users'), 'flashcards', type_='foreignkey')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.create_index('ix_flashcards_id', 'flashcards', ['id'], unique=False)
    op.drop_column('flashcards', 'user_id')
    # ### end Alembic commands ###
